"""Blueprint catalog: bundled declarative YAML definitions read from app/marketplace_catalog/.

Deliberately data (YAML), not executable Python: installing a third-party blueprint in Loonie
never means running someone else's code in this app — every blueprint is just a manifest plus a
list of scenario descriptions, executed through the same trusted prompt/runner logic
(services/marketplace_runner.py) for every publisher. This is a stricter, safer subset of the
standalone `localagents` package's code-based blueprints (see the sibling `localagents` repo's
docs/architecture/blueprint-marketplace.md), chosen specifically for the in-app marketplace
where blueprints may come from parties Loonie itself hasn't reviewed.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

import yaml

CATALOG_DIR = Path(__file__).resolve().parents[1] / "marketplace_catalog"

DEFAULT_SPECIALIST_PROMPT = (
    "You are a stress-test specialist. You only ever reason from the verified figures you are "
    "given — never invent or estimate numbers. Given one shock scenario and the client's real "
    "financial figures, write a short (3-4 sentence) internal note: how would this scenario "
    "affect them, and how resilient are they to it?"
)
DEFAULT_LEAD_PROMPT = (
    "You are the lead advisor presenting stress-test results directly to your client. You have "
    "specialist notes for several shock scenarios plus their headline figures — all already "
    "verified, computed facts. Never invent numbers beyond what you were given. Write a clear, "
    "client-facing summary: 1) overall resilience readout, 2) scenario-by-scenario summary "
    "(most concerning first), 3) concrete next steps. Keep it under 300 words and end with "
    "exactly this line: {disclaimer}"
)
DEFAULT_DISCLAIMER = (
    "This is an automated, informational stress test generated by a local LLM from your own "
    "computed figures — it is not personalized financial advice and should not be the sole "
    "basis for any financial decision."
)


@dataclass
class BlueprintScenario:
    id: str
    description: str


@dataclass
class BlueprintDefinition:
    id: str
    name: str
    publisher: str
    version: str
    tier: str  # free | paid
    price_usd: float | None
    category: str
    summary: str
    inputs: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    scenarios: list[BlueprintScenario] = field(default_factory=list)
    specialist_system_prompt: str = DEFAULT_SPECIALIST_PROMPT
    lead_system_prompt: str = DEFAULT_LEAD_PROMPT
    disclaimer: str = DEFAULT_DISCLAIMER


def _parse(raw: dict) -> BlueprintDefinition:
    scenarios = [BlueprintScenario(id=s["id"], description=s["description"]) for s in raw.get("scenarios", [])]
    return BlueprintDefinition(
        id=raw["id"],
        name=raw["name"],
        publisher=raw["publisher"],
        version=str(raw.get("version", "0.1.0")),
        tier=raw.get("tier", "free"),
        price_usd=raw.get("price_usd"),
        category=raw.get("category", "general"),
        summary=raw.get("summary", ""),
        inputs=raw.get("inputs") or [],
        tags=raw.get("tags") or [],
        scenarios=scenarios,
        specialist_system_prompt=raw.get("specialist_system_prompt") or DEFAULT_SPECIALIST_PROMPT,
        lead_system_prompt=raw.get("lead_system_prompt") or DEFAULT_LEAD_PROMPT,
        disclaimer=raw.get("disclaimer") or DEFAULT_DISCLAIMER,
    )


@lru_cache
def load_catalog() -> list[BlueprintDefinition]:
    if not CATALOG_DIR.exists():
        return []
    definitions = []
    for path in sorted(CATALOG_DIR.glob("*.yaml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        definitions.append(_parse(raw))
    return definitions


def get_blueprint(blueprint_id: str) -> BlueprintDefinition:
    for definition in load_catalog():
        if definition.id == blueprint_id:
            return definition
    raise KeyError(f"Unknown blueprint: {blueprint_id}")
