"""initial schema

Revision ID: 82a8e2647cb8
Revises: 
Create Date: 2026-09-14 22:31:41.504975
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '82a8e2647cb8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agent_execution_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_ref', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_execution_logs_user_id'), ['user_id'], unique=False)

    op.create_table('wealth_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('is_liquid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('wealth_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_categories_user_id'), ['user_id'], unique=False)

    op.create_table('wealth_forecast_assumptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('annual_return_rate', sa.Float(), nullable=False),
    sa.Column('inflation_rate', sa.Float(), nullable=False),
    sa.Column('years_horizon', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_forecast_assumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_forecast_assumptions_user_id'), ['user_id'], unique=False)

    op.create_table('wealth_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_goals_user_id'), ['user_id'], unique=False)

    op.create_table('wealth_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('facts_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_insights_user_id'), ['user_id'], unique=False)

    op.create_table('wealth_budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('monthly_amount', sa.Float(), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('critical_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['wealth_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_budgets_user_id'), ['user_id'], unique=False)

    op.create_table('wealth_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_interval', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wealth_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['wealth_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wealth_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_wealth_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wealth_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_wealth_entries_entry_date'))

    op.drop_table('wealth_entries')
    with op.batch_alter_table('wealth_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_budgets_user_id'))

    op.drop_table('wealth_budgets')
    with op.batch_alter_table('wealth_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_insights_user_id'))

    op.drop_table('wealth_insights')
    with op.batch_alter_table('wealth_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_goals_user_id'))

    op.drop_table('wealth_goals')
    with op.batch_alter_table('wealth_forecast_assumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_forecast_assumptions_user_id'))

    op.drop_table('wealth_forecast_assumptions')
    with op.batch_alter_table('wealth_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_categories_user_id'))

    op.drop_table('wealth_categories')
    with op.batch_alter_table('wealth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wealth_accounts_user_id'))

    op.drop_table('wealth_accounts')
    with op.batch_alter_table('agent_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_execution_logs_user_id'))

    op.drop_table('agent_execution_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
